# Generated by Django 3.0.6 on 2021-10-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu_data',
        ),
    ]
