# Generated by Django 3.0.6 on 2021-10-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_site', '0002_delete_menu_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(blank=True, max_length=20, null=True)),
                ('menu_category1', models.CharField(blank=True, max_length=20, null=True)),
                ('menu_category2', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient1', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient2', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient3', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient4', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient5', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient6', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient7', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient8', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient9', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient10', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient11', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient12', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient13', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient14', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient15', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient16', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient17', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient18', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient19', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient20', models.CharField(blank=True, max_length=20, null=True)),
                ('recipe', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('register_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RECIPE',
                'managed': False,
            },
        ),
    ]
