# Generated by Django 3.0.6 on 2021-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0003_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, max_length=1, null=True)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'RECIPE_RECORD',
                'managed': False,
            },
        ),
    ]
